from django.conf.urls import *

urlpatterns = patterns('env.views',
	url(r'^copyright_license', 'copyright_license'),
	url(r'^index', 'index'),
	url(r'^values_quick','values_quick'),
	url(r'^values/(.+)','values'),
	url(r'^values','values'),
	url(r'^plot','plot'),
	url(r'^highcharts','highcharts'),
	url(r'^difference','difference'),
	url(r'^data_table/(.+)/(.+)/(.+)','data_table'),
	url(r'^data_table/(.+)/(.+)','data_table'),
	url(r'^data_table','data_table'),
	url(r'^stats/(.+)/(.+)','stats'),
	url(r'^stats/(.+)','stats'),
	url(r'^stats','stats'),
	url(r'^post_data', 'post_data'),
	url(r'^sync_to_file','sync_to_file'),
	url(r'^stop_sqlite_engine','stop_sqlite_engine'),
	url(r'^load_initial_data','load_initial_data'),
	url(r'^load_test_cases','load_test_cases'),
	url(r'^testvalue','testvalue'),
	url(r'^sinevalue','sinevalue'),
	url(r'^sawtoothvalue','sawtoothvalue'),
	url(r'^logvalue','logvalue'),
	url(r'^randomvalue','randomvalue'),
	url(r'^urls','urls'),
	url(r'^docstring/(.+)','docstring'),
	url(r'^active_interfaces','active_interfaces'),
#	url(r'^all_sensors', 'all_sensors'),
#	url(r'^active_sensors', 'active_sensors'),
	url(r'^env_data_table', 'env_data_table'),
	url(r'^active_env_data_table', 'active_env_data_table'),
	url(r'^id_plot/(.+)/(.+)/(.+)/(.+)','id_plot'),
	url(r'^id_plot/(.+)/(.+)/(.+)','id_plot'),
	url(r'^serverlog/(.+)','serverlog'),
	url(r'^serverlog','serverlog'),
		
	url(r'^controller_urls', 'controller_urls'),
	
	url(r'^', 'index'),
)
